In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt

In [9]:
import numpy as np
import pandas as pd

In [10]:
digits = load_digits()

In [11]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [12]:
from sklearn.model_selection import train_test_split

In [7]:
X_train , X_test , y_train , y_test = train_test_split(digits.data, digits.target , test_size=0.3)

In [13]:
lr = LogisticRegression()

In [14]:
lr.fit(X_train , y_train)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
lr.score(X_test , y_test)

0.9574074074074074

In [16]:
svm = SVC()

In [18]:
svm.fit(X_train , y_train)

SVC()

In [19]:
svm.score(X_test, y_test)

0.9925925925925926

In [20]:
rm = RandomForestClassifier(n_estimators=40)

In [21]:
rm.fit(X_train , y_train)

RandomForestClassifier(n_estimators=40)

In [22]:
rm.score(X_test , y_test)

0.9685185185185186

In [23]:
from sklearn.model_selection import KFold

In [24]:
kf = KFold(n_splits=3)

In [25]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index , test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [26]:
def get_score(model , X_train , X_test , y_train , y_test):
    model.fit(X_train , y_train)
    return model.score(X_test , y_test)

In [ ]:
get_score(LogisticRegression() , X_train , X_test , Y_train , Y_test)

In [27]:
from sklearn.model_selection import StratifiedKFold

In [ ]:
folds = StratifiedKFold(n_splits=3)
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index , test_index in folds.split(digits.data ,digits.target):
    X_train , X_test , y_train , y_test = train_test_split(digits.data[train_index] , digits.data[test_index], digits.target[train_index] , digits.target[test_index])
    scores_logistic.append()
    